name: lamp_ecommerce_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^0.20.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: 
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway/Raleway-Light.ttf
        weight: 100
      - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        weight: 700
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        weight: 100
      - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        weight: 700

  - family: Lato
    fonts:
      - asset: assets/fonts/Lato/Lato-Regular.ttf
      - asset: assets/fonts/Lato/Lato-Light.ttf
        weight: 100
      - asset: assets/fonts/Lato/Lato-Bold.ttf
        weight: 700
